image: gitpod/workspace-dotnet:latest

tasks:  
    - name: Scraper API
      before: cd backend/Discapp.API
      init: dotnet restore
      command: dotnet watch run
      openMode: split-left

    - name: Scraper Processor
      before: cd backend/Discapp.Worker
      init: dotnet restore
      command: dotnet watch run
      openMode: split-right

    - name: Frontend
      before: cd app
      init: |
          npm i -g @ionic/cli
          npm ci
      command: |
          npm i -g @ionic/cli
          ionic serve

ports:
    - name: App
      port: 8100
    - name: Scraper
      port: 5132
